### ISSUE TITLE
如何捕获到mobike请求包

### ISSUE THREAD

**Issue by yeahx** [yrjyrj123/MobikeAgent#2]
Hi，
    想问下如何才能捕获mobike app的请求包，因为我通过设置http代理貌似也无法抓到mobikeagent中的api包。

**Comment by yrjyrj123** [comment]
因为mobike app没用使用系统默认的http库，所以全局代理无效。如果你是ios版的话，由于使用了https，貌似还验证了证书，所以也不能用代理来抓的。提示你一下，尝试反编译android的app，或者直接看我的代码，就一个api。
