### ISSUE TITLE
建议加入坐标转换功能

### ISSUE THREAD

**Issue by xdcxdc** [yrjyrj123/MobikeAgent#3]
摩拜服务器返回坐标采用的是与高德相同的GCJ02坐标系。
为了与Google Earth匹配以及其他分析需要，应该转换为WGS 1984坐标。
坐标转换可参考 https://github.com/wandergis/coordTransform_py 。

**Comment by yrjyrj123** [comment]
原来还有火星坐标系这东西，长见识了，我还以为是GPS定位不准呢。感谢小伙伴儿的建议，已经更新啦。
