### ISSUE TITLE
获取的数据有问题

### ISSUE THREAD

**Issue by zhuang-hao-ming** [yrjyrj123/MobikeAgent#4]
作者你好.
不知道您有没有注意到,这个接口返回的数据,是非常的无意义的.
我在摩拜的手机端app测试显示,在没有登录的状态下,app页面显示的附件单车是随机生成的,
只有在登录状态下,才显示正确的单车位置.不知道作者您有没有对应的处理方法?

**Comment by yrjyrj123** [comment]
刚才测试了一下，果然如此，看来摩拜单车学精了。我能想到的两个思路，一个是用ios或者微信的接口试试，看看是不是也有这个限制。另一个思路就是想办法模拟登陆过程，把cookies或者header带上，不过这种办法很快摩拜就能通过id识别出是谁再爬数据。不过好在有代收验证码的平台，可以有N多手机号来注册。我会想想办法来解决，谢谢你的反馈
